### PR TITLE
Change the dependency declaration for Apache commons

### PR DESCRIPTION
**Pull request by unexpected62**
See issue #18 

Fix a bug which caused apps to be incompatible with all devices on Google Play
    
 - See http://stackoverflow.com/a/28759797/1172494 for why this is necessary

### CODE REVIEW

**Comment by unexpected62** [comment]
@aurman who is looking at pull requests these days?

**Comment by unexpected62** [comment]
@ryanseys Are you able to accept this pull request?

**Comment by aurman** [comment]
@daveecker-nest could you take a look?

**Comment by daveecker-nest** [comment]
Looks good to me.

**Comment by unexpected62** [comment]
@aurman @daveecker-nest thanks very much guys!

**Pull request merged**
