### PR TITLE
Fix incorrect API name.

### PR DESCRIPTION
**Pull request by gdaniels**
Typo in your README. :)

### CODE REVIEW

**Comment by ryanseys** [comment]
Great, can you sign the CLA?

**Comment by gdaniels** [comment]
Just getting the appropriate person here (who's traveling right now) to sign the corporate CLA - obvs no rush here, but will do by early next week.  Thanks!

**Comment by gdaniels** [comment]
Should be all set with the CLA now.

**Comment by gdaniels** [comment]
Aw jeez, belay that. I need to change the email associated with that commit to my work one, which is in the CLA group. Will do once I get home tonight. #sigh

**Comment by gdaniels** [comment]
OK, so I re-did the commit with the correct CLA'ed email addy (glen@intrepid.io), and then force pushed this PR.  Let me know if that's ok, or if you need me to re-fork or something.  Thanks.

**Comment by ryanseys** [comment]
Thanks @gdaniels sorry for the delay!

**Pull request merged**
