### PR TITLE
Revise final classes

### PR DESCRIPTION
**Pull request by Vandalko**
It's all about testing...
Nest SDK can be divided into 4 types of classes
 - Devices
 - Listeners
 - Setters
 - Update info holder / Update data

All public listeners are just interfaces and can be easily used.

`DeviceUpdate` and `GlobalUpdate` should either have visible constructor or allow to easily mock them (I prefer first variant since why have you mock POJO classes...)

Devices (like Thermostat or Structure) are basically a POJO classes, mapped with annotations to JSON structure. They don't have setters so I assume they are designed to be instantiated only by `ObjectMapper`.

Setters are wrappers around Firebase and should be easily mocked for testing.

**However**, there is another point of view on testing problem.
We can call `Firebase.goOffline()` before the tests to ensure that we are running locally and build abstraction layer around NestAPI to avoid direct interactions during test.
But I don't really like this approach because NestAPI is just abstraction layer around Firebase and I don't want to build a cake :)

P.S. In general, this PR aims to get understanding why `ThermostatSetter` is final but `StructureSetter` is not; same question for `Camera` and `Thermostat` ?

### CODE REVIEW

**Comment by ryanseys** [comment]
I probably just screwed up and didn't make everything final that really should be. 

The idea is that all Update classes should be final (because they represent the state of the system at a specific point in time and thus should be considered immutable). Additionally, the POJO classes Thermostat, Camera, Metadata, SmokeCOAlarm, should also all be final. Also, the Setter classes were created to provide a better API to the end developer such that they can call 

```java
myNestApi.cameras.turnOnline();
```

rather than cluttering up the NestAPI class with methods like "`myNestApi.turnOnCamera()`". So in this way the `Setter` classes should likely also be final.

We don't need public constructors for `Update` classes because we don't want developers creating instances of these objects themselves. They can be created in tests using these non-public constructors or Mocking test frameworks.

Regarding, Firebase.goOffline(), I don't want to do that because I'd rather mimic a real life request scenario and mock the surrounding environment by capturing the request and checking its validity.

**Comment by Vandalko** [comment]
AFAIK, at least Mockito, is not able mock final classes that's why I've remove `final` from Setters.
But it's still possible to access constructors with default visibility (due to Java nature) to construct Update classes.

**Comment by ryanseys** [comment]
I don't see why you couldn't mock a final class. I know you can't modify final variables within a class, but that's another issue altogether.

But also, if we can get away with testing some functionality without mocking a class, that's always better.

**Comment by Vandalko** [comment]
well, that's the limitation of Mockito, but the one can use Powermock...

as for testing without mocking - unfortunately I don't see the way to hack Firebase underneath the NestAPI to test the chain:
Authenticate using token -> Update device state -> Receive updated state

**Comment by Vandalko** [comment]
I've updated the PR code...

**Comment by ryanseys** [comment]
If you want to test that entire flow, now you're talking about system tests which shouldn't mock anything. If you want to mock things, you should test each of those steps individually.

**Comment by Vandalko** [comment]
closing this for now.
For people who have faced same frustration using Mockito, I recommend to try https://github.com/robolectric/robolectric/wiki/Using-PowerMock

**Pull request closed without merging**
